// <auto-generated />
using System;
using EMS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMS.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EMS.API.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2b$12$jei01JjrfO5xWk9y9awMEO8AjahTa7DspG9eGCgzBnVJ4S4pbeUUe",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2b$12$wlln8Oe9N1fsvoD6kS6Me.vPqoVxaYCdqAMpejhB0nq2r//T31W1S",
                            Role = "Viewer",
                            Username = "viewer"
                        });
                });

            modelBuilder.Entity("EMS.API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Designation = "Software Engineer",
                            Email = "priya.prabhu@hexacore.com",
                            FirstName = "Priya",
                            JoinDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Prabhu",
                            Phone = "9876543210",
                            Salary = 850000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Marketing",
                            Designation = "Marketing Executive",
                            Email = "arjun.sharma@hexacore.com",
                            FirstName = "Arjun",
                            JoinDate = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Sharma",
                            Phone = "9123456780",
                            Salary = 620000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2019, 11, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "HR",
                            Designation = "HR Executive",
                            Email = "neha.kapoor@hexacore.com",
                            FirstName = "Neha",
                            JoinDate = new DateTime(2019, 11, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Kapoor",
                            Phone = "9988776655",
                            Salary = 550000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2019, 11, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Finance",
                            Designation = "Financial Analyst",
                            Email = "rahul.verma@hexacore.com",
                            FirstName = "Rahul",
                            JoinDate = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Verma",
                            Phone = "9876512340",
                            Salary = 720000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2018, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Operations",
                            Designation = "Operations Manager",
                            Email = "sneha.prasad@hexacore.com",
                            FirstName = "Sneha",
                            JoinDate = new DateTime(2018, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Prasad",
                            Phone = "9001234567",
                            Salary = 950000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2018, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2017, 9, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Designation = "Senior Developer",
                            Email = "vikram.nair@hexacore.com",
                            FirstName = "Vikram",
                            JoinDate = new DateTime(2017, 9, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Raj",
                            Phone = "9871234560",
                            Salary = 1100000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2017, 9, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 2, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Marketing",
                            Designation = "Content Strategist",
                            Email = "ananya.singh@hexacore.com",
                            FirstName = "Ananya",
                            JoinDate = new DateTime(2023, 2, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Singh",
                            Phone = "9765432100",
                            Salary = 580000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2023, 2, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2020, 4, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Finance",
                            Designation = "Accounts Manager",
                            Email = "karthik.rajan@hexacore.com",
                            FirstName = "Karthik",
                            JoinDate = new DateTime(2020, 4, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Rajan",
                            Phone = "9654321098",
                            Salary = 800000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2020, 4, 17, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 8, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "HR",
                            Designation = "Talent Acquisition Lead",
                            Email = "divya.kumar@hexacore.com",
                            FirstName = "Divya",
                            JoinDate = new DateTime(2021, 8, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Kumar",
                            Phone = "9543210987",
                            Salary = 690000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2021, 8, 22, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2019, 3, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Finance",
                            Designation = "Tax Consultant",
                            Email = "suresh.babu@hexacore.com",
                            FirstName = "Suresh",
                            JoinDate = new DateTime(2019, 3, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Babu",
                            Phone = "9432109876",
                            Salary = 760000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2019, 3, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2022, 10, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Designation = "QA Engineer",
                            Email = "meera.krishnan@hexacore.com",
                            FirstName = "Meera",
                            JoinDate = new DateTime(2022, 10, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Krishnan",
                            Phone = "9321098765",
                            Salary = 730000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2022, 10, 11, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2020, 12, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Marketing",
                            Designation = "Brand Manager",
                            Email = "lakshmi.chandran@hexacore.com",
                            FirstName = "Lakshmi",
                            JoinDate = new DateTime(2020, 12, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Chandran",
                            Phone = "9210987654",
                            Salary = 870000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2020, 12, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 5, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Operations",
                            Designation = "Supply Chain Analyst",
                            Email = "amit.joshi@hexacore.com",
                            FirstName = "Amit",
                            JoinDate = new DateTime(2021, 5, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Joshi",
                            Phone = "9109876543",
                            Salary = 640000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2021, 5, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Designation = "DevOps Engineer",
                            Email = "pooja.ghosh@hexacore.com",
                            FirstName = "Pooja",
                            JoinDate = new DateTime(2023, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Ghosh",
                            Phone = "9098765432",
                            Salary = 980000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2023, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2020, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Operations",
                            Designation = "Logistics Coordinator",
                            Email = "ravi.menon@hexacore.com",
                            FirstName = "Ravi",
                            JoinDate = new DateTime(2020, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Menon",
                            Phone = "8987654321",
                            Salary = 590000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2020, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
